<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>recyclebin5385.eclipse.accessorjavadoc</groupId>
  <artifactId>accessorjavadoc-parent</artifactId>
  <version>0.1.2-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>plugins/recyclebin5385.eclipse.plugin.accessorjavadoc</module>
    <module>features/recyclebin5385.eclipse.feature.accessorjavadoc</module>
    <module>repository</module>
    <module>releng/target</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <tycho.version>4.0.8</tycho.version>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-maven-plugin</artifactId>
        <version>${tycho.version}</version>
        <extensions>true</extensions>
      </plugin>
      
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-p2-repository-plugin</artifactId>
        <version>${tycho.version}</version>
        <configuration>
          <compress>false</compress>
        </configuration>
      </plugin>
    </plugins>
  </build>
  
  <repositories>
    <repository>
      <id>eclipse</id>
     <layout>p2</layout>
      <url>https://download.eclipse.org/releases/2024-06</url>
    </repository>
  </repositories>
</project>